name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Leap Year
      id: leap-year
      uses: education/autograding-io-grader@v1
      with:
        test-name: Leap Year
        setup-command: ''
        command: node leap-year.js
        input: ''
        expected-output: |-
          false
          false
          true
          true
          false
          false
          true
          true
          false
        comparison-method: contains
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        LEAP-YEAR_RESULTS: "${{steps.leap-year.outputs.result}}"
      with:
        runners: leap-year
